version: "3"

services:
  mysite:
    build: .
    image: mysite:a1
    container_name: mysite
    restart: on-failure
    command: python manage.py runserver 0.0.0.0:8017
    volumes:
      - "./mysite/:/mysite/"
    ports:
      - 8017:8017

  solr:
    image: solr:8.10.1
    container_name: solr
    ports:
      - 8983:8983
    volumes:
      - "./solr_data:/var/solr/data"